"""MOQT (Media over QUIC Transport) のプロトコル層。

draft-ietf-moq-transport-21 の codec と sans I/O セッション状態機械を公開する。
この層はストリームの実体に触れない。呼び出し側が peer のストリーム種別を判定して
`Session.receive_*` を呼び、戻り値の `Event` に従ってバイト列を送る。

WebTransport を介した client / server は `moqt.moq` が提供する。
このモジュールは、ワイヤのバイト列を直接組み立てて検証するテストや、実装が送出した
バイト列を検査するテストから使う。

`Event.parameters` と `Message.parameters` はパラメータを「型番号をキーにした
エンコード済みバイト列の辞書」として返す。同じ形式の辞書が `Session.send_*` と
`moqt.moq` の `parameters` 引数に対する入力であり、受信した辞書をそのまま送信経路へ
渡せる。draft が定める値の型と意味で読み書きする場合は `MessageParameters` を使う。
`LocationFilter` は `LOCATION_FILTER` の型付き表現であり、辞書の値としてそのまま
渡せる。

MOQT は draft 由来であり、将来の改訂で変更される可能性がある。
"""

from collections.abc import Callable

from moqt import _native
from moqt._native import (
    Event,
    LocationFilter,
    LocationFilterUpdate,
    Message,
    MessageParameters,
    ObjectProperties,
    Session,
    TrackProperties,
    classify_data_stream_type,
    decode_message,
    decode_parameter,
    decode_varint,
    decode_varint_prefix,
    encode_varint,
    is_padding_datagram,
    setup_stream_type,
)

# SUBSCRIBER_PRIORITY の既定値
# (draft-ietf-moq-transport-21 §9.20.6 (SUBSCRIBER_PRIORITY Parameter))
DEFAULT_SUBSCRIBER_PRIORITY: int = 128

# ストリーム種別
# (draft-ietf-moq-transport-21 §6.4.1 (Unidirectional Streams) Table 3)
SETUP_STREAM_TYPE: int = _native.SETUP_STREAM_TYPE
FETCH_HEADER_TYPE: int = _native.FETCH_HEADER_TYPE
PADDING_STREAM_TYPE: int = _native.PADDING_STREAM_TYPE
PADDING_DATAGRAM_TYPE: int = _native.PADDING_DATAGRAM_TYPE

# メッセージパラメータ
# (draft-ietf-moq-transport-21 §9.20 (Control Message Parameters))
PARAM_OBJECT_DELIVERY_TIMEOUT: int = _native.PARAM_OBJECT_DELIVERY_TIMEOUT
PARAM_AUTHORIZATION_TOKEN: int = _native.PARAM_AUTHORIZATION_TOKEN
PARAM_SUBGROUP_DELIVERY_TIMEOUT: int = _native.PARAM_SUBGROUP_DELIVERY_TIMEOUT
PARAM_EXPIRES: int = _native.PARAM_EXPIRES
PARAM_LARGEST_OBJECT: int = _native.PARAM_LARGEST_OBJECT
PARAM_FILL_TIMEOUT: int = _native.PARAM_FILL_TIMEOUT
PARAM_FORWARD: int = _native.PARAM_FORWARD
PARAM_SUBSCRIBER_PRIORITY: int = _native.PARAM_SUBSCRIBER_PRIORITY
PARAM_LOCATION_FILTER: int = _native.PARAM_LOCATION_FILTER
PARAM_GROUP_ORDER: int = _native.PARAM_GROUP_ORDER
PARAM_FILL_PARAMETERS: int = _native.PARAM_FILL_PARAMETERS
PARAM_SUBGROUP_FILTER: int = _native.PARAM_SUBGROUP_FILTER
PARAM_OBJECTID_FILTER: int = _native.PARAM_OBJECTID_FILTER
PARAM_PRIORITY_FILTER: int = _native.PARAM_PRIORITY_FILTER
PARAM_OBJECT_PROPERTY_FILTER: int = _native.PARAM_OBJECT_PROPERTY_FILTER
PARAM_TRACK_PROPERTY_FILTER: int = _native.PARAM_TRACK_PROPERTY_FILTER
PARAM_NEW_GROUP_REQUEST: int = _native.PARAM_NEW_GROUP_REQUEST
PARAM_TRACK_NAMESPACE_PREFIX: int = _native.PARAM_TRACK_NAMESPACE_PREFIX
PARAM_INCLUDE_PROPERTIES: int = _native.PARAM_INCLUDE_PROPERTIES

# SETUP オプションの型番号
# (draft-ietf-moq-transport-21 §9.1 (SETUP))
SETUP_OPTION_PATH: int = _native.SETUP_OPTION_PATH
"""PATH。クライアントが要求する path。"""

SETUP_OPTION_AUTHORIZATION_TOKEN: int = _native.SETUP_OPTION_AUTHORIZATION_TOKEN
"""AUTHORIZATION_TOKEN。"""

SETUP_OPTION_MAX_AUTH_TOKEN_CACHE_SIZE: int = _native.SETUP_OPTION_MAX_AUTH_TOKEN_CACHE_SIZE
"""MAX_AUTH_TOKEN_CACHE_SIZE。"""

SETUP_OPTION_AUTHORITY: int = _native.SETUP_OPTION_AUTHORITY
"""AUTHORITY。"""

SETUP_OPTION_MAX_FILTER_RANGES: int = _native.SETUP_OPTION_MAX_FILTER_RANGES
"""MAX_FILTER_RANGES。"""

SETUP_OPTION_MOQT_IMPLEMENTATION: int = _native.SETUP_OPTION_MOQT_IMPLEMENTATION
"""MOQT_IMPLEMENTATION。実装名。"""

SETUP_OPTION_MAX_REQUEST_UPDATES: int = _native.SETUP_OPTION_MAX_REQUEST_UPDATES
"""MAX_REQUEST_UPDATES。"""

# REQUEST_ERROR のコード
# (draft-ietf-moq-transport-21 §16.11.2 (REQUEST_ERROR Codes))
REQUEST_INTERNAL_ERROR: int = _native.REQUEST_INTERNAL_ERROR
REQUEST_UNAUTHORIZED: int = _native.REQUEST_UNAUTHORIZED
REQUEST_TIMEOUT: int = _native.REQUEST_TIMEOUT
REQUEST_NOT_SUPPORTED: int = _native.REQUEST_NOT_SUPPORTED
REQUEST_MALFORMED_AUTH_TOKEN: int = _native.REQUEST_MALFORMED_AUTH_TOKEN
REQUEST_EXPIRED_AUTH_TOKEN: int = _native.REQUEST_EXPIRED_AUTH_TOKEN
REQUEST_GOING_AWAY: int = _native.REQUEST_GOING_AWAY
REQUEST_EXCESSIVE_LOAD: int = _native.REQUEST_EXCESSIVE_LOAD
REQUEST_DOES_NOT_EXIST: int = _native.REQUEST_DOES_NOT_EXIST
REQUEST_INVALID_RANGE: int = _native.REQUEST_INVALID_RANGE
REQUEST_MALFORMED_TRACK: int = _native.REQUEST_MALFORMED_TRACK
REQUEST_UNINTERESTED: int = _native.REQUEST_UNINTERESTED
REQUEST_PREFIX_OVERLAP: int = _native.REQUEST_PREFIX_OVERLAP
REQUEST_NAMESPACE_TOO_LARGE: int = _native.REQUEST_NAMESPACE_TOO_LARGE
REQUEST_UNSUPPORTED_EXTENSION: int = _native.REQUEST_UNSUPPORTED_EXTENSION
REQUEST_REDIRECT: int = _native.REQUEST_REDIRECT
REQUEST_CONFLICTING_FILTERS: int = _native.REQUEST_CONFLICTING_FILTERS
REQUEST_INVALID_FILTER: int = _native.REQUEST_INVALID_FILTER

# PUBLISH_DONE のコード
# (draft-ietf-moq-transport-21 §16.11.3 (PUBLISH_DONE Codes))
PUBLISH_DONE_INTERNAL_ERROR: int = _native.PUBLISH_DONE_INTERNAL_ERROR
PUBLISH_DONE_UNAUTHORIZED: int = _native.PUBLISH_DONE_UNAUTHORIZED
PUBLISH_DONE_TRACK_ENDED: int = _native.PUBLISH_DONE_TRACK_ENDED
PUBLISH_DONE_GOING_AWAY: int = _native.PUBLISH_DONE_GOING_AWAY
PUBLISH_DONE_TOO_FAR_BEHIND: int = _native.PUBLISH_DONE_TOO_FAR_BEHIND
PUBLISH_DONE_EXPIRED: int = _native.PUBLISH_DONE_EXPIRED
PUBLISH_DONE_UPDATE_FAILED: int = _native.PUBLISH_DONE_UPDATE_FAILED
PUBLISH_DONE_EXCESSIVE_LOAD: int = _native.PUBLISH_DONE_EXCESSIVE_LOAD
PUBLISH_DONE_MALFORMED_TRACK: int = _native.PUBLISH_DONE_MALFORMED_TRACK

# ストリーム reset のコード
# (draft-ietf-moq-transport-21 §16.11.4 (Stream Reset Codes))
STREAM_INTERNAL_ERROR: int = _native.STREAM_INTERNAL_ERROR
STREAM_CANCELLED: int = _native.STREAM_CANCELLED
STREAM_DELIVERY_TIMEOUT: int = _native.STREAM_DELIVERY_TIMEOUT
STREAM_SESSION_CLOSED: int = _native.STREAM_SESSION_CLOSED
STREAM_GOING_AWAY: int = _native.STREAM_GOING_AWAY
STREAM_TOO_FAR_BEHIND: int = _native.STREAM_TOO_FAR_BEHIND
STREAM_UNKNOWN_OBJECT_STATUS: int = _native.STREAM_UNKNOWN_OBJECT_STATUS
STREAM_EXPIRED_AUTH_TOKEN: int = _native.STREAM_EXPIRED_AUTH_TOKEN
STREAM_EXCESSIVE_LOAD: int = _native.STREAM_EXCESSIVE_LOAD
STREAM_MALFORMED_TRACK: int = _native.STREAM_MALFORMED_TRACK

# Session Termination のコード
# (draft-ietf-moq-transport-21 §16.11.1 (Session Termination Codes))
SESSION_NO_ERROR: int = _native.SESSION_NO_ERROR
SESSION_INTERNAL_ERROR: int = _native.SESSION_INTERNAL_ERROR
SESSION_UNAUTHORIZED: int = _native.SESSION_UNAUTHORIZED
SESSION_PROTOCOL_VIOLATION: int = _native.SESSION_PROTOCOL_VIOLATION
SESSION_INVALID_REQUEST_ID: int = _native.SESSION_INVALID_REQUEST_ID
SESSION_DUPLICATE_TRACK_ALIAS: int = _native.SESSION_DUPLICATE_TRACK_ALIAS
SESSION_KEY_VALUE_FORMATTING_ERROR: int = _native.SESSION_KEY_VALUE_FORMATTING_ERROR
SESSION_INVALID_PATH: int = _native.SESSION_INVALID_PATH
SESSION_MALFORMED_PATH: int = _native.SESSION_MALFORMED_PATH
SESSION_GOAWAY_TIMEOUT: int = _native.SESSION_GOAWAY_TIMEOUT
SESSION_CONTROL_MESSAGE_TIMEOUT: int = _native.SESSION_CONTROL_MESSAGE_TIMEOUT
SESSION_DATA_STREAM_TIMEOUT: int = _native.SESSION_DATA_STREAM_TIMEOUT
SESSION_AUTH_TOKEN_CACHE_OVERFLOW: int = _native.SESSION_AUTH_TOKEN_CACHE_OVERFLOW
SESSION_DUPLICATE_AUTH_TOKEN_ALIAS: int = _native.SESSION_DUPLICATE_AUTH_TOKEN_ALIAS
SESSION_MALFORMED_AUTH_TOKEN: int = _native.SESSION_MALFORMED_AUTH_TOKEN
SESSION_UNKNOWN_AUTH_TOKEN_ALIAS: int = _native.SESSION_UNKNOWN_AUTH_TOKEN_ALIAS
SESSION_EXPIRED_AUTH_TOKEN: int = _native.SESSION_EXPIRED_AUTH_TOKEN
SESSION_INVALID_AUTHORITY: int = _native.SESSION_INVALID_AUTHORITY
SESSION_MALFORMED_AUTHORITY: int = _native.SESSION_MALFORMED_AUTHORITY
SESSION_TOO_MANY_REQUEST_UPDATES: int = _native.SESSION_TOO_MANY_REQUEST_UPDATES
SESSION_LOCAL_FILTER_MISMATCH: int = _native.SESSION_LOCAL_FILTER_MISMATCH
"""自側のフィルタ適用の結果、購読が成立しなかった。wire には出ない。"""

SESSION_LOCAL_DATAGRAM_TIMEOUT: int = _native.SESSION_LOCAL_DATAGRAM_TIMEOUT
"""自側でデータグラムの待ち合わせが期限切れになった。wire には出ない。"""

# Object Status
# (draft-ietf-moq-transport-21 §11.1.2 (Object Status))
OBJECT_STATUS_NORMAL: int = 0x0
"""通常のオブジェクト。非 0 長のオブジェクトでは暗黙の値である。"""

OBJECT_STATUS_END_OF_GROUP: int = _native.OBJECT_STATUS_END_OF_GROUP
"""指定した Object ID 以降のオブジェクトが同じ Group に存在しない。"""

OBJECT_STATUS_END_OF_TRACK: int = _native.OBJECT_STATUS_END_OF_TRACK
"""指定した Location 以降のオブジェクトが存在しない。"""

# Subgroup Header の SUBGROUP_ID_MODE (bits 1-2、mask 0x06)
# (draft-ietf-moq-transport-21 §11.3.1 (Subgroup Header))
SUBGROUP_ID_MODE_ZERO: str = _native.SUBGROUP_ID_MODE_ZERO
"""Subgroup ID を 0 に固定するモード (SUBGROUP_ID_MODE = 0b00)。"""

SUBGROUP_ID_MODE_FIRST_OBJECT_ID: str = _native.SUBGROUP_ID_MODE_FIRST_OBJECT_ID
"""最初の Object ID を Subgroup ID にするモード (SUBGROUP_ID_MODE = 0b01)。"""

SUBGROUP_ID_MODE_EXPLICIT: str = _native.SUBGROUP_ID_MODE_EXPLICIT
"""Subgroup ID フィールドを送るモード (SUBGROUP_ID_MODE = 0b10)。"""

# データグラムの合計サイズの目安。
#
# QUIC は 1200 バイトの UDP データグラムを必ず運べることを要求する
# (RFC 9000 §8.1)。DATAGRAM フレームは分割できないため、QUIC と HTTP/3 の
# オーバーヘッドを差し引いたこの値を超えるデータグラムは、経路 MTU によっては
# 通知なく破棄される。破棄は送信側から検知できない
# (draft-ietf-moq-transport-21 §11.2.1 (Object Datagram))。
#
# 経路 MTU が大きい場合 (典型的な Ethernet では 1500 バイト) はこれを超える
# データグラムも配送できるが、その上限は moqt-py からは知り得ない。
MAX_DATAGRAM_SIZE: int = 1100
"""経路に依存せず配送できるデータグラムの合計サイズ (ヘッダを含む)。"""

# PUBLISHER_PRIORITY の既定値
# (draft-ietf-moq-transport-21 §9.20.5 (PUBLISHER_PRIORITY Parameter))
PUBLISHER_PRIORITY_DEFAULT: int = _native.PUBLISHER_PRIORITY_DEFAULT

# DEFAULT_PUBLISHER_GROUP_ORDER の既定値
# (draft-ietf-moq-transport-21 §10.5 (DEFAULT PUBLISHER GROUP ORDER))
DEFAULT_PUBLISHER_GROUP_ORDER_ASCENDING: int = _native.DEFAULT_PUBLISHER_GROUP_ORDER_ASCENDING
"""Ascending。宣言が省略されたときの publisher の選好。"""

# キャンセル済み peer publisher alias の tombstone 保持期間の既定値 (ms)
# (draft-ietf-moq-transport-21 §3.1.2 (Track Alias))
DEFAULT_PEER_ALIAS_RETENTION_MS: int = _native.DEFAULT_PEER_ALIAS_RETENTION_MS
"""遅延 Object を捨てられる程度に短く、通常の再確立を妨げない値。"""

# GOAWAY の New Session URI の最大長
# (draft-ietf-moq-transport-21 §9.2 (GOAWAY))
MAX_NEW_SESSION_URI_LENGTH: int = _native.MAX_NEW_SESSION_URI_LENGTH
"""セッション移行先を示す URI の最大長 (バイト)。"""

# PUBLISH_DONE の STREAM_COUNT が不明であることを示す番兵
# (draft-ietf-moq-transport-21 §9.9 (PUBLISH_DONE))
PUBLISH_DONE_STREAM_COUNT_UNKNOWN: int = _native.PUBLISH_DONE_STREAM_COUNT_UNKNOWN
"""publisher が stream 数を表明しない場合の値。"""

# 受信済み request id の穴として保持できる件数の上限
MAX_OUT_OF_ORDER_REQUEST_IDS: int = _native.MAX_OUT_OF_ORDER_REQUEST_IDS
"""追い越して届いた request id を保持できる件数。超過は INVALID_REQUEST_ID になる。"""

# GREASE (Generate Random Extensions And Sustain Extensibility)
# (draft-ietf-moq-transport-21 §13 (Grease))
GREASE_BASE: int = _native.GREASE_BASE
"""GREASE 値の基数 (0x9D)。"""

GREASE_INTERVAL: int = _native.GREASE_INTERVAL
"""GREASE 値の間隔 (0x7F)。"""

GREASE_MAX: int = _native.GREASE_MAX
"""GREASE 値の上限 (0x3FFFFFFFFFFFFFDE)。"""

# Object Properties の型番号
# (draft-ietf-moq-transport-21 §16.8 (Properties) Table 14)
PROP_PRIOR_GROUP_ID_GAP: int = _native.PROP_PRIOR_GROUP_ID_GAP
"""直前の存在しない Group の個数 (§10.8)。"""

PROP_PRIOR_OBJECT_ID_GAP: int = _native.PROP_PRIOR_OBJECT_ID_GAP
"""直前の存在しない Object の個数 (§10.9)。"""

# Track Properties の型番号
# (draft-ietf-moq-transport-21 §16.8 (Properties) Table 14)
PROP_OBJECT_DELIVERY_TIMEOUT: int = _native.PROP_OBJECT_DELIVERY_TIMEOUT
"""Object の配送期限 (ms) (§10.2)。"""

PROP_MAX_CACHE_DURATION: int = _native.PROP_MAX_CACHE_DURATION
"""キャッシュの保持期間 (ms)。"""

PROP_SUBGROUP_DELIVERY_TIMEOUT: int = _native.PROP_SUBGROUP_DELIVERY_TIMEOUT
"""Subgroup の配送期限 (ms) (§10.1)。"""

PROP_IMMUTABLE_PROPERTIES: int = _native.PROP_IMMUTABLE_PROPERTIES
"""途中で変化しないプロパティの入れ子リスト (§10.7)。"""

PROP_DEFAULT_PUBLISHER_PRIORITY: int = _native.PROP_DEFAULT_PUBLISHER_PRIORITY
"""既定の Publisher Priority (§10.4)。"""

PROP_DEFAULT_PUBLISHER_GROUP_ORDER: int = _native.PROP_DEFAULT_PUBLISHER_GROUP_ORDER
"""既定の Group Order (§10.5)。"""

PROP_DYNAMIC_GROUPS: int = _native.PROP_DYNAMIC_GROUPS
"""Group が動的に決まるか (§10.6)。"""

MANDATORY_TRACK_PROPERTY_MIN: int = _native.MANDATORY_TRACK_PROPERTY_MIN
"""必須の Track Property の型番号の下限 (§3.6)。"""

MANDATORY_TRACK_PROPERTY_MAX: int = _native.MANDATORY_TRACK_PROPERTY_MAX
"""必須の Track Property の型番号の上限 (§3.6)。"""


def generate(source: Callable[[int], int] | None = None) -> int:
    """GREASE 値を 1 つ生成する。

    `source` は `stop` を 1 つ受け取り `[0, stop)` の整数を返す呼び出し可能
    オブジェクトである。省略すると標準ライブラリの `random.randrange` を使う。
    乱数源を渡せるため、テストでは決定的な値を再現できる。

    (draft-ietf-moq-transport-21 §13 (Grease))
    """
    return _native.generate(source)


def is_grease(value: int) -> bool:
    """値が GREASE 値かどうかを返す。

    上限 `GREASE_MAX` を超えた値も値の並びに合致すれば `True` になる。

    (draft-ietf-moq-transport-21 §13 (Grease))
    """
    return _native.is_grease(value)


__all__ = [
    "DEFAULT_PEER_ALIAS_RETENTION_MS",
    "DEFAULT_PUBLISHER_GROUP_ORDER_ASCENDING",
    "DEFAULT_SUBSCRIBER_PRIORITY",
    "FETCH_HEADER_TYPE",
    "GREASE_BASE",
    "GREASE_INTERVAL",
    "GREASE_MAX",
    "MANDATORY_TRACK_PROPERTY_MAX",
    "MANDATORY_TRACK_PROPERTY_MIN",
    "MAX_DATAGRAM_SIZE",
    "MAX_NEW_SESSION_URI_LENGTH",
    "MAX_OUT_OF_ORDER_REQUEST_IDS",
    "OBJECT_STATUS_END_OF_GROUP",
    "OBJECT_STATUS_END_OF_TRACK",
    "OBJECT_STATUS_NORMAL",
    "PADDING_DATAGRAM_TYPE",
    "PADDING_STREAM_TYPE",
    "PARAM_AUTHORIZATION_TOKEN",
    "PARAM_EXPIRES",
    "PARAM_FILL_PARAMETERS",
    "PARAM_FILL_TIMEOUT",
    "PARAM_FORWARD",
    "PARAM_GROUP_ORDER",
    "PARAM_INCLUDE_PROPERTIES",
    "PARAM_LARGEST_OBJECT",
    "PARAM_LOCATION_FILTER",
    "PARAM_NEW_GROUP_REQUEST",
    "PARAM_OBJECTID_FILTER",
    "PARAM_OBJECT_DELIVERY_TIMEOUT",
    "PARAM_OBJECT_PROPERTY_FILTER",
    "PARAM_PRIORITY_FILTER",
    "PARAM_SUBGROUP_DELIVERY_TIMEOUT",
    "PARAM_SUBGROUP_FILTER",
    "PARAM_SUBSCRIBER_PRIORITY",
    "PARAM_TRACK_NAMESPACE_PREFIX",
    "PARAM_TRACK_PROPERTY_FILTER",
    "PROP_DEFAULT_PUBLISHER_GROUP_ORDER",
    "PROP_DEFAULT_PUBLISHER_PRIORITY",
    "PROP_DYNAMIC_GROUPS",
    "PROP_IMMUTABLE_PROPERTIES",
    "PROP_MAX_CACHE_DURATION",
    "PROP_OBJECT_DELIVERY_TIMEOUT",
    "PROP_PRIOR_GROUP_ID_GAP",
    "PROP_PRIOR_OBJECT_ID_GAP",
    "PROP_SUBGROUP_DELIVERY_TIMEOUT",
    "PUBLISHER_PRIORITY_DEFAULT",
    "PUBLISH_DONE_EXCESSIVE_LOAD",
    "PUBLISH_DONE_EXPIRED",
    "PUBLISH_DONE_GOING_AWAY",
    "PUBLISH_DONE_INTERNAL_ERROR",
    "PUBLISH_DONE_MALFORMED_TRACK",
    "PUBLISH_DONE_STREAM_COUNT_UNKNOWN",
    "PUBLISH_DONE_TOO_FAR_BEHIND",
    "PUBLISH_DONE_TRACK_ENDED",
    "PUBLISH_DONE_UNAUTHORIZED",
    "PUBLISH_DONE_UPDATE_FAILED",
    "REQUEST_CONFLICTING_FILTERS",
    "REQUEST_DOES_NOT_EXIST",
    "REQUEST_EXCESSIVE_LOAD",
    "REQUEST_EXPIRED_AUTH_TOKEN",
    "REQUEST_GOING_AWAY",
    "REQUEST_INTERNAL_ERROR",
    "REQUEST_INVALID_FILTER",
    "REQUEST_INVALID_RANGE",
    "REQUEST_MALFORMED_AUTH_TOKEN",
    "REQUEST_MALFORMED_TRACK",
    "REQUEST_NAMESPACE_TOO_LARGE",
    "REQUEST_NOT_SUPPORTED",
    "REQUEST_PREFIX_OVERLAP",
    "REQUEST_REDIRECT",
    "REQUEST_TIMEOUT",
    "REQUEST_UNAUTHORIZED",
    "REQUEST_UNINTERESTED",
    "REQUEST_UNSUPPORTED_EXTENSION",
    "SESSION_AUTH_TOKEN_CACHE_OVERFLOW",
    "SESSION_CONTROL_MESSAGE_TIMEOUT",
    "SESSION_DATA_STREAM_TIMEOUT",
    "SESSION_DUPLICATE_AUTH_TOKEN_ALIAS",
    "SESSION_DUPLICATE_TRACK_ALIAS",
    "SESSION_EXPIRED_AUTH_TOKEN",
    "SESSION_GOAWAY_TIMEOUT",
    "SESSION_INTERNAL_ERROR",
    "SESSION_INVALID_AUTHORITY",
    "SESSION_INVALID_PATH",
    "SESSION_INVALID_REQUEST_ID",
    "SESSION_KEY_VALUE_FORMATTING_ERROR",
    "SESSION_LOCAL_DATAGRAM_TIMEOUT",
    "SESSION_LOCAL_FILTER_MISMATCH",
    "SESSION_MALFORMED_AUTHORITY",
    "SESSION_MALFORMED_AUTH_TOKEN",
    "SESSION_MALFORMED_PATH",
    "SESSION_NO_ERROR",
    "SESSION_PROTOCOL_VIOLATION",
    "SESSION_TOO_MANY_REQUEST_UPDATES",
    "SESSION_UNAUTHORIZED",
    "SESSION_UNKNOWN_AUTH_TOKEN_ALIAS",
    "SETUP_OPTION_AUTHORITY",
    "SETUP_OPTION_AUTHORIZATION_TOKEN",
    "SETUP_OPTION_MAX_AUTH_TOKEN_CACHE_SIZE",
    "SETUP_OPTION_MAX_FILTER_RANGES",
    "SETUP_OPTION_MAX_REQUEST_UPDATES",
    "SETUP_OPTION_MOQT_IMPLEMENTATION",
    "SETUP_OPTION_PATH",
    "SETUP_STREAM_TYPE",
    "STREAM_CANCELLED",
    "STREAM_DELIVERY_TIMEOUT",
    "STREAM_EXCESSIVE_LOAD",
    "STREAM_EXPIRED_AUTH_TOKEN",
    "STREAM_GOING_AWAY",
    "STREAM_INTERNAL_ERROR",
    "STREAM_MALFORMED_TRACK",
    "STREAM_SESSION_CLOSED",
    "STREAM_TOO_FAR_BEHIND",
    "STREAM_UNKNOWN_OBJECT_STATUS",
    "SUBGROUP_ID_MODE_EXPLICIT",
    "SUBGROUP_ID_MODE_FIRST_OBJECT_ID",
    "SUBGROUP_ID_MODE_ZERO",
    "Event",
    "LocationFilter",
    "LocationFilterUpdate",
    "Message",
    "MessageParameters",
    "ObjectProperties",
    "Session",
    "TrackProperties",
    "classify_data_stream_type",
    "decode_message",
    "decode_parameter",
    "decode_varint",
    "decode_varint_prefix",
    "encode_varint",
    "generate",
    "is_grease",
    "is_padding_datagram",
    "setup_stream_type",
]
